[project]
authors = ["chrisjw42 <chrisjw42@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "classification"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.11"
flask = ">=3.0.3,<4"
pytest = ">=8.3.3,<9"
pytest-mock = ">=3.14.0,<4"